config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  # verb "path", to: "controller#action"

  # homepage
  root to: 'tasks#home'

  # show all
  get 'tasks', to: 'tasks#index'

  # create a task
  # .1 create a form
  get 'tasks/new', to: 'tasks#new', as: 'task_new'
  # .2 send the form
  post 'tasks', to: 'tasks#create'

  # show 1
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  # edit task
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'

  # delete a task
  delete 'tasks/:id', to: 'tasks#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :show, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/tasks/_form.html.erb
<%# <%= form_for task do |t| %>
<%# <%= t.label :title %>
<%# <%= t.text_field :title %>
<%# <%= t.label :details %>
<%# <%= t.text_field :details %>
<%# <%= t.label :completed %>
<%# <%= t.text_field :completed %>
<%# <%= t.submit%>
<%# <% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <br><h1>Edit a task</h1><hr>

  <%= simple_form_for @task do |d| %>
    <%= d.input :title, placeholder: 'washing the dishes' %>
    <%= d.input :details, placeholder: '1 hour do to this task' %>
    <%= d.input :completed, collection: ['true', 'false']%>
    <%= d.button :submit, class: "btn btn-primary" %>
    <%= link_to "back to task", tasks_path, class: 'btn btn-danger' %>
  <% end %>
  <br><br>
</div>



<%# <%= d.collection_check_boxes :completed, [[true, 'Completed']], :first, :last %>

<%# <%= render 'form', task: @task %>

app/views/tasks/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://blog.seguridade.com.br/wp-content/uploads/2017/04/como-gerenciar-tarefas-da-minha-equipe-de-forma-efetiva-810x810.jpeg.webp);">
  <div class="container">
    <h1>A way to do your task and mark if you done the task or not</strong>!</h1>
    <p>easy to work, just enjoy it.</p>
    <%= link_to "Start the task manager!", tasks_path, class: "btn btn-success" %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <br><h1>My tasks📃</h1><br>
    <%= link_to task_new_path do %>
      <i class="fa-solid fa-plus"></i><span class="badge rounded-pill bg-primary">Create a task</span>
    <% end %> <hr>

  <ul>
    <% @tasks.each do |task| %>
      <li>
        <% if task.completed? %>
          <i class="fa-solid fa-square-check"></i>
        <% else %>
          <i class="fa-regular fa-square"></i>
        <% end %>
        <%= link_to task.title, task_path(task) %>
        <%= link_to task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
          <i class="fa-regular fa-trash-can"></i>
          <% end %>
      </li>
    <% end %>
  </ul>
  <hr>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Tasks</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Mark</td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Jacob</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td colspan="2">Larry the Bird</td>
      </tr>
    </tbody>
  </table>
</div>


<%# <ul>
  <% @tasks.each do |task| %>
    <%# <li>
      <% if task.completed? %>
        <%# <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
          <label class="form-check-label" for="flexCheckChecked">
          </label>
          <%= link_to task.title, task_path(task) %>
            <%# <%= link_to task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
              <%# <i class="fa-regular fa-trash-can"></i>
            <% end %>
        <%# </div>
      <% else %>
        <%# <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
          <label class="form-check-label" for="flexCheckDefault">
          <%= link_to task.title, task_path(task) %>
          <%# </label>
          <%= link_to task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
            <%# <i class="fa-regular fa-trash-can"></i>
          <% end %>
        <%# </div>
      <% end %>
    <%# </li>
  <% end %>
<%# </ul> %>

app/views/tasks/new.html.erb
<div class="container">
  <br><h1>Create a new task</h1><hr>
  <%= simple_form_for @task do |d| %>
    <%= d.input :title, placeholder: 'washing the dishes' %>
    <%= d.input :details, placeholder: '1 hour do to this task' %>
    <%= d.input :completed, collection: ['true', 'false']%>
    <%= d.button :submit, class: "btn btn-primary btn-sm" %>
    <%= link_to tasks_path do %>
      <i class="fa-solid fa-arrow-rotate-left"></i><span class="badge rounded-pill bg-primary">Back to tasks</span>
    <% end %>
  <% end %>
  <br><br>
</div>
  <%# <%= d.collection_check_boxes :completed, [[true, 'Completed']], :first, :last %>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1><%= @task.title %></h1>
    <%= link_to edit_task_path(@task.id), class: 'btn btn-light btn-sm border' do %>
      <i class="fa fa-pencil"></i> Edit this task
    <% end %>
  </div>

<div class="card-category">
  <p><%= @task.details %></p>
</div>
<br>
  <% if @task.completed %>
    <i class="fa-solid fa-square-check"></i> This task is completed
  <% else %>
    <i class="fa-regular fa-square"></i> This task is not completed yet
  <% end %>

  <hr>
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i><span class="badge rounded-pill bg-primary">Back to tasks</span>
  <% end %>
</div>